name: Test

on: [workflow_dispatch]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Install ndk
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: 26.3.11579264
          local-cache: true
