name: Test

on: [workflow_dispatch]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Install Android SDK Manager
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;26.3.11579264'
