name: Test

on: [workflow_dispatch]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Install Android SDK Manager
        uses: android-actions/setup-android@v3
        with:
          packages: ''
      - name: Install NDK
        run: |
          sdkmanager --install "ndk;26.3.11579264"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.3.11579264" >> $GITHUB_ENV
          echo $ANDROID_SDK_ROOT